spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mimea-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
# 关闭session
  session:
    store-type: none

security:
  basic:
    enabled: false
